### ISSUE TITLE
ExAirtable.create/2 cleaning out cache

### ISSUE THREAD

**Issue by stevelead** [dmerand/ex_airtable#3]
Thanks for sharing this project and the great docs, articles etc.

I'm currently running into an issue. Each time I create a record or records with ExAirtable.create/2 the table's cache is cleaned out. 

It looks like this might be due to ":set_all" in:

` job =
        Request.create(
          {table_module, :create, [smaller_list]},
          {TableCache, :set_all, [table_module]}`

Changing `:set_all` to `:update` seems to solve the problem.

**Comment by iffies** [comment]
Yes, @stevelead, I think you're correct. Did you change your mind when you closed the issue?

**Comment by stevelead** [comment]
Hi, I still think solution above is correct, only closed as issue had been open for so long
