### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by weaversam8** [dmerand/ex_airtable#7]
Hi there. This project appears to be intended to be MIT licensed, per the Hex config:

https://github.com/dmerand/ex_airtable/blob/a0897a1aecc6cf08d76e8841851ced6e2c5ee122/mix.exs#L50

However, no license is present in a file at the root of the repository. Would you consider adding a LICENSE file to clarify this?

**Comment by dmerand** [comment]
@weaversam8 Sure - wanna post a PR with a license?

**Comment by weaversam8** [comment]
Done, created #8.
